config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'display' => 'static_pages#display'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'vendors/index'
  get 'vendors/autoimport' => 'vendors#autoimport'
  get 'auth/:provider/callback', to: 'sessions#facebookcreate'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    resources :history_entries, only: [:create, :destroy]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :vendors do
    collection {post :import}
    resources :comments, only: [:create, :destroy]
  end

  
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @vendors = Vendor.autoimport
    if params[:search]
      @vendors = Vendor.search(params[:search])
    else
      @vendors = Vendor.order(:key)
    end
    @list_vendors = @vendors
    gon.vendors = @vendors
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>
<h1>About</h1>
<p> We are the team Stratton Oakmont. This is our project for CPSC310 at UBC.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact us at here!
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>
<h1>Help</h1>
<p>In order to get help please say "Help me please!" loudly so that we can hear you.</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <% if logged_in? %>
    <%= render 'shared/map' %>
    <br />
    <center><h3><%= link_to "See Vendor Pages", vendors_path %></h3></center>
    <%= form_tag(root_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Vendors" %>
      <%= submit_tag "Search",  :class => "btn btn-default", :name => nil%>
    <% end %>
        
  <% else %>
    <h1>Vancouver Vendor Diary</h1>
    <h2>Welcome to the visualization of <a href=" http://data.vancouver.ca/datacatalogue/foodVendors.htm"><em>Vendors of  Vancouver</em></a></h2>
    <center><h4>Feeling hungry? Here you can locate food vendors in Vancouver and share your thoughts with other users!</h4></center><br>
    <center><%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %></center></br>
    <div id="user_nav">  
       <center><%= link_to "Sign in with facebook", "/auth/facebook", id: "sign_in", class: "btn btn-lg btn-primary" %></center>
    </div> 
    <center><%= link_to image_tag("VVD.png", alt: "Team SO logo"), root_path %></center>
  <% end %>
</div>