config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'display' => 'static_pages#display'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'vendors/index'
  get 'vendors/autoimport' => 'vendors#autoimport'
  get 'auth/:provider/callback', to: 'sessions#facebookcreate'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    resources :history_entries, only: [:create, :destroy]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :vendors do
    collection {post :import}
    resources :comments, only: [:create, :destroy]
  end

  
  

end

app/models/history_entry.rb
class HistoryEntry < ActiveRecord::Base
  default_scope -> { order(created_at: :desc) }

  belongs_to :user
  belongs_to :vendor

  validates :user_id, presence: true
  validates :vendor_id, presence: true
  validates :date_time, presence: true
end

app/controllers/history_entries_controller.rb
class HistoryEntriesController < ApplicationController
  # before_action :set_history_entry, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:create, :destroy]

  # @history_entries = HistoryEntry.all

  def create
    @vendor = Vendor.find(params[:vid])

    if @vendor
      @history_entry = HistoryEntry.new
      @history_entry.user = current_user
      @history_entry.vendor = @vendor
      @history_entry.date_time = DateTime.now

      if @history_entry.save
        flash[:success] = "Checked in successfully!"
      end
      redirect_to @vendor
    else
      redirect_to root_url, :alert => "You can't check in."
    end
  end

  def destroy
    @history_entry.destroy
    flash[:success] = "History entry deleted"
    redirect_to request.referrer || root_url
  end

  private
    def set_history_entry
      @history_entry = HistoryEntry.find(params[:id])
    end

    def history_entry_params
      params.require(:history_entry).permit(:date_time, :user_id, :vendor_id)
    end
end

app/helpers/history_entries_helper.rb
module HistoryEntriesHelper
end

app/views/history_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing History Entries</h1>

<table>
  <thead>
    <tr>
      <th>Date time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @history_entries.each do |history_entry| %>
      <tr>
        <td><%= history_entry.date_time %></td>
        <td><%= link_to 'Show', history_entry %></td>
        <td><%= link_to 'Edit', edit_history_entry_path(history_entry) %></td>
        <td><%= link_to 'Destroy', history_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History entry', new_history_entry_path %>