config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'display' => 'static_pages#display'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'vendors/index'
  get 'vendors/autoimport' => 'vendors#autoimport'
  get 'auth/:provider/callback', to: 'sessions#facebookcreate'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    resources :history_entries, only: [:create, :destroy]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :vendors do
    collection {post :import}
    resources :comments, only: [:create, :destroy]
  end

  
  

end

app/views/shared/_comment_form.html.erb
<%= form_for ([@vendor, @comment]) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new comment..."%>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_comments.html.erb
<div class="col-md-8">
  <h3>Comments (<%= object.comments.count %>)</h3>
  <% if object.comments.any? %>
    <ol class="comments">
      <%= render @comments %>
    </ol>
    <%= will_paginate @comments %>
  <% else %>
    Explore the map and have something delicious! Leave a comment if your stomach is as happy as you are :)
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_history_entries.html.erb
<div class="col-md-8">
  <h3>History (<%= object.history_entries.count %>)</h3>
  <% if object.history_entries.any? %>
    <ul class="comments">
      <% object.history_entries.each do |he| %>
        <li><%= he.date_time %> | <%= link_to "#{Vendor.find(he.vendor_id).business_name}", vendor_path(he.vendor_id) %></li>
      <% end %>
    </ul>
  <% else %>
    You haven't been anywhere yet! You can check in at a vendor through their page.
  <% end %>
</div>

app/views/shared/_history_entry_form.html.erb
<% if current_omniauthuser %> 
  <%= button_to "Check In", user_history_entries_path(current_user, :vid => @vendor.id), class: 'btn btn-primary' %>
<%end%>

app/views/shared/_map.html.erb
<h1>Vendors of Vancouver</h1>
<center><button type="button" id="switch" onclick="switchView()">Switch to List View</button></center>

<div id="map">
  <div id="map-container">
    <div id="map-canvas"></div>
  </div>
</div>

<div id="list">
  <br />
  <table border = "1">
    <tr>
      <th>Business Name</th>
      <th>Location</th>
      <th>Description</th>
    </tr>

    <% @list_vendors.each do |v| %>
    <tr>
      <td><li><%= link_to v.business_name, v %></li></td>
      <td><%= v.location %></td>
      <td><%= v.description %></td>
    </tr>
    <% end %>
  </table>
</div>

<script type="text/javascript">loadScript();</script>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.comments.count, "comment") %></span>

app/views/shared/_vmap.html.erb
<div id="map">
  <div id="vmap-container">
    <div id="vmap-canvas"></div>
  </div>
</div>
<script type="text/javascript">loadScript2();</script>